services:
  frontend:
    image: frontend
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    ports:
      - "3000:3000"
  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
  db:
    image: postgres
    expose:
      - 5432

volumes:
  node_modules:
  build: